import React, { useState, useEffect } from "react";
import Head from "next/head";
import { NavBar } from "../NavBar/NavBar";
import { Footer } from "../footer/component";

export const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>C Long - Sze Long</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <main className="min-h-screen font-sans bg-lightTheme dark:bg-darkTheme transition-colors -z-10 m-0">
        {children}
      </main>
      <Footer />
    </div>
  );
};
